"""
Django settings for anuri project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from django.contrib.messages import constants as messages

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'r5m-77x%owmzr$2o9x29+o#+qsnvsl#orxns8k3egg&rl+d^b$#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True



#Email Setting
EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST_USER = "arinzesuccess2@gmail.com"
EMAIL_HOST_PASSWORD = "bright1008"
EMAIL_PORT = "587"
EMAIL_USE_TLS = True

# Application definition

INSTALLED_APPS = [
    'dal',
    'dal_select2',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',


    # External apps
    'versatileimagefield',
    'babeldjango',
    'bootstrap3',
    'selectable',
    'datetimewidget',
    'django_tables2',
    # 'crispy_forms',
    'fm',
    'smart_selects',
    'channels',
    'rolepermissions',
    'rest_framework',
    'bootstrap3_datetime',
    'easy_select2',

    # local apps
    'userprofile',
    'registration',
    'extension',
    'phonenumber_field',
    'popup',
    'report',
    'django_cron',
    'dispatcher',
    'bio',
    'ami',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.CountryMiddleware',
    'core.middleware.CurrencyMiddleware',
]
CRON_CLASSES = [
    "popup.cron.MyCronJob",
    # ...
]
ROOT_URLCONF = 'anuri.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'anuri.wsgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgi_redis.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("localhost", 6379)],
        },
        "ROUTING": "anuri.routing.channel_routing",
    },
}

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'creodb',
#         'USER': 'root',
#         'PASSWORD': 'Ezearinze1008@1',
#         'HOST': 'localhost',
#         'PORT': '',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'creodb',
        'USER': 'postgres',
        'PASSWORD': 'W3lc0m3123',
        'HOST': 'localhost',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static_in_pro", "../static_in_env/static_root")
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static_in_pro","our_static"),
    # '/var/www/static/',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.abspath(os.path.join(BASE_DIR, '../../../../var/spool/asterisk/monitor'))
# MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static_in_pro", '../../../../var/spool/asterisk/monitor')

SITE_ID = 1

AUTH_USER_MODEL = 'userprofile.User'

LOGIN_URL = '/account/login'

DEFAULT_CURRENCY = 'NGN'
AVAILABLE_CURRENCIES = [DEFAULT_CURRENCY]
DEFAULT_WEIGHT = 'lb'

ACCOUNT_ACTIVATION_DAYS = 3

LOGIN_REDIRECT_URL = 'home'
LOGIN_REDIRECT_URL_AUTH = '/profile'

SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'

MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}
FACEBOOK_APP_ID = os.environ.get('FACEBOOK_APP_ID')
FACEBOOK_SECRET = os.environ.get('FACEBOOK_SECRET')

GOOGLE_ANALYTICS_TRACKING_ID = os.environ.get('GOOGLE_ANALYTICS_TRACKING_ID')
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET')

PAGINATE_BY = 16

TEST_RUNNER = ''
# CKEDITOR_JQUERY_URL = 'https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js'
# ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost').split()
ALLOWED_HOSTS = ['*']
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CRISPY_TEMPLATE_PACK = 'bootstrap3'
# AUDIO_DIRS = [
#     os.path.abspath(BASE_DIR, "static_in_pro","our_static","audio","monitor"),
# ]
AUDIO_DIRS = [os.path.abspath(os.path.join(BASE_DIR, '../../../../var/spool/asterisk/monitor'))]
ROLEPERMISSIONS_MODULE = 'core.roles'
# ROLEPERMISSIONS_REDIRECT_TO_LOGIN = True