# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agentid', models.CharField(blank=True, max_length=255, null=True, verbose_name='agentid')),
                ('agentname', models.CharField(blank=True, max_length=255, null=True, verbose_name='agentname')),
                ('agentstatus', models.CharField(blank=True, max_length=255, null=True, verbose_name='agentstatus')),
                ('timestamp', models.CharField(blank=True, max_length=255, null=True, verbose_name='timestamp')),
                ('callid', models.FloatField(blank=True, max_length=255, null=True, verbose_name='callid')),
                ('queue', models.CharField(blank=True, max_length=255, null=True, verbose_name='time')),
            ],
        ),
        migrations.CreateModel(
            name='BitAgentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agentid', models.CharField(blank=True, max_length=255, null=True, verbose_name='agentid')),
                ('agentname', models.CharField(blank=True, max_length=255, null=True, verbose_name='agentname')),
                ('agentstatus', models.CharField(blank=True, max_length=255, null=True, verbose_name='agentstatus')),
                ('timestamp', models.CharField(blank=True, max_length=255, null=True, verbose_name='timestamp')),
                ('callid', models.FloatField(blank=True, max_length=255, null=True, verbose_name='callid')),
                ('queue', models.CharField(blank=True, max_length=255, null=True, verbose_name='time')),
            ],
        ),
        migrations.CreateModel(
            name='CallStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callid', models.CharField(blank=True, max_length=255, null=True, verbose_name='callis')),
                ('callerid', models.CharField(blank=True, max_length=255, null=True, verbose_name='callerid')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='status')),
                ('timestamp', models.CharField(blank=True, max_length=255, null=True, verbose_name='timestamp')),
                ('queue', models.FloatField(blank=True, max_length=255, null=True, verbose_name='queue')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='position')),
                ('originalposition', models.CharField(blank=True, max_length=255, null=True, verbose_name='originalposition')),
                ('holdtime', models.CharField(blank=True, max_length=255, null=True, verbose_name='holdtime')),
                ('keypressed', models.CharField(blank=True, max_length=255, null=True, verbose_name='keypressed')),
                ('callduration', models.CharField(blank=True, max_length=255, null=True, verbose_name='callduration')),
            ],
        ),
        migrations.CreateModel(
            name='Cdr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(blank=True, max_length=255, null=True, verbose_name='src')),
                ('dst', models.CharField(blank=True, max_length=255, null=True, verbose_name='dst')),
                ('dcontext', models.CharField(blank=True, max_length=255, null=True, verbose_name='dcontext')),
                ('clid', models.CharField(blank=True, max_length=255, null=True, verbose_name='clid')),
                ('channel', models.CharField(blank=True, max_length=255, null=True, verbose_name='channel')),
                ('dstchannel', models.CharField(blank=True, max_length=255, null=True, verbose_name='dstchannel')),
                ('lastapp', models.CharField(blank=True, max_length=255, null=True, verbose_name='lastapp')),
                ('lastdata', models.CharField(blank=True, max_length=255, null=True, verbose_name='lastdata')),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('billsec', models.IntegerField(blank=True, null=True)),
                ('disposition', models.CharField(blank=True, max_length=255, null=True, verbose_name='disposition')),
                ('amaflags', models.IntegerField(blank=True, null=True)),
                ('uniqueid', models.CharField(blank=True, max_length=255, null=True, verbose_name='uniqueid')),
                ('calldate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hour')),
            ],
        ),
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hour')),
            ],
        ),
        migrations.CreateModel(
            name='QueryTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_from', models.CharField(blank=True, max_length=255, null=True)),
                ('month_from', models.CharField(blank=True, max_length=255, null=True)),
                ('day_from', models.CharField(blank=True, max_length=255, null=True)),
                ('year_to', models.CharField(blank=True, max_length=255, null=True)),
                ('month_to', models.CharField(blank=True, max_length=255, null=True)),
                ('day_to', models.CharField(blank=True, max_length=255, null=True)),
                ('hour_from', models.CharField(blank=True, max_length=255, null=True)),
                ('minute_from', models.CharField(blank=True, max_length=255, null=True)),
                ('hour_to', models.CharField(blank=True, max_length=255, null=True)),
                ('minute_to', models.CharField(blank=True, max_length=255, null=True)),
                ('agents', models.TextField(blank=True, null=True)),
                ('ext', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=255, null=True, verbose_name='time')),
                ('callid', models.CharField(blank=True, max_length=255, null=True, verbose_name='callid')),
                ('queuename', models.CharField(blank=True, max_length=255, null=True, verbose_name='queuename')),
                ('agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='agent')),
                ('event', models.CharField(blank=True, max_length=255, null=True, verbose_name='event')),
                ('data1', models.CharField(blank=True, max_length=255, null=True, verbose_name='data1')),
                ('data2', models.CharField(blank=True, max_length=255, null=True, verbose_name='data2')),
                ('data3', models.CharField(blank=True, max_length=255, null=True, verbose_name='data3')),
                ('data4', models.CharField(blank=True, max_length=255, null=True, verbose_name='data4')),
                ('data5', models.CharField(blank=True, max_length=255, null=True, verbose_name='data5')),
            ],
        ),
    ]
