# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-17 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0003_auto_20170208_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentBreak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_out', models.DateTimeField(auto_now_add=True)),
                ('time_in', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='userprofile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Breaks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Breaks',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='last name')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='phone')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='city')),
                ('street', models.TextField(verbose_name='Street')),
                ('geo_auto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Geo Political')),
                ('state_auto', models.CharField(blank=True, max_length=255, null=True, verbose_name='State')),
                ('lga_auto', models.CharField(blank=True, max_length=255, null=True, verbose_name='LGA')),
                ('city_auto', models.CharField(blank=True, max_length=255, null=True, verbose_name='city')),
                ('street_auto', models.TextField(verbose_name='Street')),
                ('latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Longitude')),
                ('injured_citizen', models.CharField(blank=True, max_length=255, null=True, verbose_name='injured citizen')),
                ('inc_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Casualty Number')),
                ('incident_location', models.CharField(max_length=255, verbose_name='Incident Location')),
                ('channel', models.CharField(blank=True, max_length=255, null=True, verbose_name='channel')),
                ('context', models.CharField(blank=True, max_length=255, null=True, verbose_name='context')),
                ('dispatch_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('entered_out', models.DateTimeField(auto_now_add=True, null=True)),
                ('note', models.TextField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_agent', to='userprofile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Emergency name')),
            ],
        ),
        migrations.CreateModel(
            name='Geopolitical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Geopolitical Zones',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('priority', models.CharField(max_length=255, verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
        migrations.CreateModel(
            name='INumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Number of Incidence',
            },
        ),
        migrations.CreateModel(
            name='Lga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'LGA',
            },
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respondent', to='popup.Emergency')),
            ],
            options={
                'verbose_name_plural': 'Respondents',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geopolitical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popup.Geopolitical')),
            ],
            options={
                'verbose_name_plural': 'State',
            },
        ),
        migrations.AddField(
            model_name='lga',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popup.State'),
        ),
        migrations.AddField(
            model_name='case',
            name='emergencies',
            field=models.ManyToManyField(to='popup.Emergency'),
        ),
        migrations.AddField(
            model_name='case',
            name='geopolitical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popup.Geopolitical'),
        ),
        migrations.AddField(
            model_name='case',
            name='lga',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='popup.Lga'),
        ),
        migrations.AddField(
            model_name='case',
            name='respondent',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='emergencies', chained_model_field='emergency', to='popup.Respondent'),
        ),
        migrations.AddField(
            model_name='case',
            name='state',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='geopolitical', chained_model_field='geopolitical', on_delete=django.db.models.deletion.CASCADE, to='popup.State'),
        ),
        migrations.AddField(
            model_name='agentbreak',
            name='breaks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='popup.Breaks'),
        ),
    ]
