# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-17 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergency',
            options={'verbose_name_plural': 'Emergencies'},
        ),
    ]
