# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-17 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0004_auto_20170217_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='inc_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='number', to='popup.INumber'),
        ),
    ]
