# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-17 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0005_auto_20170217_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='agent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='agent'),
        ),
    ]
