# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-17 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0006_auto_20170217_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
