# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-20 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0007_auto_20170217_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_auto', models.CharField(blank=True, max_length=255, null=True, verbose_name='State')),
                ('lga_auto', models.CharField(blank=True, max_length=255, null=True, verbose_name='LGA')),
                ('city_auto', models.CharField(blank=True, max_length=255, null=True, verbose_name='city')),
                ('location_auto', models.CharField(blank=True, max_length=255, null=True, verbose_name='location')),
                ('latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Longitude')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='phone')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='last name')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name='state')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='phone')),
                ('community', models.CharField(blank=True, max_length=255, null=True, verbose_name='city')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='location')),
                ('injured_citizen', models.CharField(blank=True, max_length=255, null=True, verbose_name='injured citizen')),
                ('channel', models.CharField(blank=True, max_length=255, null=True, verbose_name='channel')),
                ('context', models.CharField(blank=True, max_length=255, null=True, verbose_name='context')),
                ('dispatch_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('entered_out', models.DateTimeField(auto_now_add=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='agent')),
                ('emergencies', models.ManyToManyField(to='popup.Emergency')),
                ('inc_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casuality_number', to='popup.INumber')),
                ('respondent', smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='emergencies', chained_model_field='emergency', to='popup.Respondent')),
            ],
        ),
    ]
