# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-20 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0009_auto_20170220_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='state'),
        ),
    ]
