# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-20 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0010_auto_20170220_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statet', to='popup.State'),
        ),
    ]
