# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-23 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0013_agentdispatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Communities',
            },
        ),
        migrations.AlterField(
            model_name='account',
            name='city_auto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='popup.Community'),
        ),
        migrations.AlterField(
            model_name='agentdispatch',
            name='community',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community2', to='popup.Community'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='community',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community1', to='popup.Community'),
        ),
    ]
