# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-23 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0014_auto_20170223_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='city_auto',
        ),
        migrations.AddField(
            model_name='account',
            name='community',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='community'),
        ),
    ]
