# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-23 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0015_auto_20170223_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community1', to='popup.Community'),
        ),
    ]
