# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0019_auto_20170309_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentbreak',
            name='time_spent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentdispatch',
            name='dispatch_duration',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='duration'),
        ),
        migrations.AddField(
            model_name='agentdispatch',
            name='sent_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentdispatch',
            name='dispatch_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
