# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0024_loginlogout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='case',
            name='emergencies',
        ),
        migrations.RemoveField(
            model_name='case',
            name='geopolitical',
        ),
        migrations.RemoveField(
            model_name='case',
            name='inc_number',
        ),
        migrations.RemoveField(
            model_name='case',
            name='lga',
        ),
        migrations.RemoveField(
            model_name='case',
            name='respondent',
        ),
        migrations.RemoveField(
            model_name='case',
            name='state',
        ),
        migrations.DeleteModel(
            name='Case',
        ),
    ]
