# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0025_auto_20170324_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoaxTracer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='number')),
                ('set_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
