# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-01 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(default='101', max_length=255, verbose_name='AgentID')),
                ('extension_secret', models.CharField(max_length=255, verbose_name='Password')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='first name')),
            ],
        ),
        migrations.CreateModel(
            name='Hoax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Review Period Name')),
            ],
        ),
        migrations.CreateModel(
            name='HoaxDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Review Period Name')),
            ],
        ),
        migrations.CreateModel(
            name='HoaxSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_period', models.CharField(blank=True, max_length=255, null=True, verbose_name='Review Period')),
                ('number_hoax', models.CharField(blank=True, max_length=255, null=True, verbose_name='Allowable Frequency')),
                ('placed_hoax', models.CharField(blank=True, max_length=255, null=True, verbose_name='Period Placed as Hoax (days)')),
                ('in_next_days', models.CharField(blank=True, max_length=255, null=True, verbose_name='Number of Days')),
                ('hoax_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hoax', to='extension.Hoax')),
            ],
        ),
        migrations.CreateModel(
            name='SipExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Display Name')),
                ('extension', models.CharField(max_length=255, unique=True, verbose_name='User Extension')),
                ('type', models.CharField(choices=[(b'peer', 'Peer'), (b'user', 'User'), (b'friend', 'Friend')], default='peer', max_length=255, verbose_name='type')),
                ('secret', models.CharField(max_length=255, verbose_name='secret')),
                ('username', models.CharField(max_length=255, verbose_name='username')),
                ('host', models.CharField(default='dynamic', max_length=255, verbose_name='host')),
                ('fromuser', models.CharField(blank=True, max_length=255, null=True, verbose_name='fromuser')),
                ('fromdomain', models.CharField(blank=True, max_length=255, null=True, verbose_name='fromdomain')),
                ('canreinvite', models.CharField(choices=[(b'yes', 'Yes'), (b'no', 'No')], default='no', max_length=255, verbose_name='canreinvite')),
                ('insecure', models.CharField(default='invite,port', max_length=255, verbose_name='insecure')),
                ('qualify', models.CharField(choices=[(b'yes', 'Yes'), (b'no', 'No')], default='yes', max_length=255, verbose_name='qualify')),
                ('nat', models.CharField(choices=[(b'yes', 'Yes'), (b'no', 'No')], default='yes', max_length=255, verbose_name='nat')),
                ('context', models.CharField(default='from-internal', max_length=255, verbose_name='context')),
                ('bindport', models.CharField(default='5060', max_length=255, verbose_name='bindport')),
                ('srvlookup', models.CharField(choices=[(b'yes', 'Yes'), (b'no', 'No')], default='yes', max_length=255, verbose_name='srvloopup')),
                ('disallow', models.CharField(default='all', max_length=255, verbose_name='disallow')),
                ('allow', models.CharField(default='ulaw,alaw,gsm', max_length=255, verbose_name='allow')),
            ],
        ),
        migrations.CreateModel(
            name='Sync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=256, verbose_name='ip')),
                ('ext', models.CharField(max_length=256, verbose_name='ext')),
            ],
        ),
    ]
